#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

#  sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restarts the Nginx service to apply the configuration changes.
sudo service nginx restart
