#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404_page.html

new_string="server_name _;\n\n\terror_page 404 \/custom_404_page.html;\n\tlocation = \/custom_404_page.html"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_strings="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com;\n\t}"

sudo sed -i "s/server_name _;/$new_strings/" /etc/nginx/sites-enabled/default

# Creating an HTTP response header
news_string="server_name _;\n\n\t# Add a custom header \n\n\tadd_header X-Served-By \$hostname;\n"

sudo sed -i "s/server_name _;/$news_string/" /etc/nginx/sites-enabled/default

# Restart nginx after implementing changes
sudo service nginx restart
